### PR TITLE
Capabilities for PhantomJs and upgrade to Selenium 2.46.0

### PR DESCRIPTION
**Pull request by jlamaille**
Add phantomjs capabilities and upgrade Selenium version to 2.46.0.

### CODE REVIEW

**Comment by smccarthy** [comment]
Hi @jlamaille . Is there any way you can split off the PRs from PhantomJS and selenium 2.46.0 ? I think it would be easier to review and merge in. If not, no worries.

**Comment by smccarthy** [comment]
Is the phantomjsdriver in this PR a forked copy of detro's version? I wasn't sure if https://github.com/detro/ghostdriver was still an active project. Also, is the version from codeborne on github somewhere?

**Comment by jlamaille** [comment]
Yes, you are right, I took this version of phantomjs for another project, I will back to the correct groupId.
Also, I will do two pull requests. One for upgrading to 2.46 and the other for integrating phantomjs.
However, the second depend on the first.

**Comment by smccarthy** [comment]
Ok, I was planning on merging in the first one (upgrade to 2.46.0) anyway, as its a lot easier. I saw you also included a dependency for Opera. Was that intentional?

**Comment by jlamaille** [comment]
Yes, the dependency for opera was intentional.

**Comment by jlamaille** [comment]
Hi, i have dependencies problems to add phantomJs capabilities :
 - Detro release (http://mvnrepository.com/artifact/com.github.detro.ghostdriver/phantomjsdriver/1.1.0) use version 2.39.0 for selenium-remote-driver
 - Codeborne Realease (http://mvnrepository.com/artifact/com.codeborne/phantomjsdriver/1.2.1) use version 2.44.0 for selenium-remote-driver

Currently, Selenium-Grid-Extras use version 2.42.0 for selenium-remote-driver. What is your preference ?

**Pull request closed without merging**
