### PR TITLE
Changes config parsing to be able to use selenium 3.13+.

### PR DESCRIPTION
**Pull request by damencho**
Contains some changes that are covered in https://github.com/groupon/Selenium-Grid-Extras/pull/402

### CODE REVIEW

**Comment by damencho** [comment]
Can you tell me, what tests do you run? And how you run it and I can try looking at it.
The changes I pushed, we are running for more than 6 months without a problem.

**Comment by damencho** [comment]
I suppose the tests ran by maven (sorry, I'm on the mobile). I will check it.

**Comment by shankarkc** [comment]
Thanks a lot @damencho I used grid extra created from your git repository with selenium grid version `3.14.0` With this combination nodes failed to register with hub.

**Comment by damencho** [comment]
Hum, now I see I had made mistake creating those PR's. I think I initially started working on the branch 2.x, and our fork we are using is based on that branch, but I created the PR's against master ... I need to further check it ...

**Pull request closed without merging**
