### PR TITLE
Adding/ Updating maven-compiler-plugin

### PR DESCRIPTION
**Pull request by asnir**

### CODE REVIEW

**Comment by smccarthy** [comment]
Hi @asnir . What does the maven-compiler-plugin give us?

Thank you!

**Comment by asnir** [comment]
Compiling the code without errors.

> Sometimes when you may need to compile a certain project to a different version than what you are currently using. The javac can accept such command using -source and -target. The Compiler Plugin can also be configured to provide these options during compilation.

**Comment by asnir** [comment]
@smccarthy , do you plan to merge it?

**Comment by smccarthy** [comment]
@asnir Sure, merging now. Sorry it took so long.

**Pull request merged**
