### PR TITLE
Adding ability to mention servlets in selenium 3.0 configuration

### PR DESCRIPTION
**Pull request by shankarkc**
Bug : https://github.com/groupon/Selenium-Grid-Extras/issues/286
Fixing the Node config by adding servlet config section back as some of us are using this section to provide additional capabilities like Sikuli( seleniumGrid Extension)

### CODE REVIEW

**Comment by smccarthy** [comment]
Looks good. Merging !

**Comment by shankarkc** [comment]
@smccarthy  when can I expect a new build with this change?

**Comment by shankarkc** [comment]
@smccarthy  i created one more rull request to handle NULL check that i missed. Can you pls merge it? 
https://github.com/groupon/Selenium-Grid-Extras/pull/350
Thanks
Shankar KC

**Comment by shankarkc** [comment]
I did test https://github.com/groupon/Selenium-Grid-Extras/pull/352 this time with all scenarios( with servlet present/absent). Hopefully there wont be any issues now.

**Pull request merged**
