### PR TITLE
#167 - Allow turning on/off the SessionHistory feature.

### PR DESCRIPTION
**Pull request by charlescapps**
This pull request allows turning off the SessionHistory feature. It is still on by default.

### CODE REVIEW

**Comment by smccarthy** [comment]
@charlescapps Is it possible to write a test for this feature?

**Comment by charlescapps** [comment]
Yeah, I could do that. At the very least verify the default config. Or a functional test to verify the log files are not generated. Will add a commit within a few days.

**Comment by smccarthy** [comment]
Thank you very much!

**Comment by charlescapps** [comment]
Hi Shawn,

I just added tests in SetupTeardownProxy that use mockito so we can test if Session logging is configured without needing to actually stand up a Selenium Grid. 

Also adding an assertion to RuntimeConfigTest so that we verify session logging is ON by default.
They are passing.

Cheers,
Charles

**Comment by charlescapps** [comment]
Rad, thanks!

**Pull request merged**
